3mf_path = "export/3mf/"
step_path = "export/step/"
stl_path = "export/stl/"

[document]
id = "6a1de9567f16cd7d1f564dbb"
workspace_id = "da2053ce82593768f41daab4"

[[part_studio]]
display_name = "Printables"
id = "59628be740b2cf41a42e4c8a"
